name: auto publish website
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  publish-website:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps: 
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: '16.x'
      - name: use cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/pnpm-lock')}}
      - name: install pnpm  
        run: npm install pnpm -g
      - name: install dependencies
        run: pnpm i
      - name: build website
        run: pnpm site:build
      - name: publish 
         uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # 打包后的文件在哪里
          FOLDER: website/docs/.vuepress/dist



